### ISSUE TITLE
Master branch outdated

### ISSUE THREAD

**Issue by carusogabriel** [phpcommunity/phptestfest-php-src#157]
Open this issue to discuss the update of the `phptestfest-2017-master` branch, or create a `master` branch itself, that will be up-to-date with upstream for future PHP Test Fests.

**Comment by ramsey** [comment]
I can update it and/or set up a process to keep it updated, but as @petk [mentioned on internals](https://externals.io/message/104224#104225):

> A separate fork out of the php/php-src was not such a good idea.

So, whomever runs TestFest next can work with internals in a better way that helps streamline this process better and ensures these contributions don't get forgotten or outdated.

**Comment by petk** [comment]
I think we can manage with the repository in the current state... Your call.

**Comment by ramsey** [comment]
I've rebased `phptestfest-2017-master` with `php/php-src` master, and I've also added a new `master` branch to this repo.

**Comment by ramsey** [comment]
For some background, the reason we had a separate `phptestfest-2017-master` branch named that way was because I had intended that all the approved PRs would get merged into it, and then we could submit one big PR to `php/php-src`, and since all the smaller ones had already been reviewed by core devs, it could just be accepted in with one merge.

**Comment by carusogabriel** [comment]
@ramsey Makes sense, I liked this idea. For future PHP Test Fests, let's make this way.
